services:
  weaviate:
    image: semitechnologies/weaviate:latest
    container_name: weaviate
    environment:
      - QUERY_DEFAULTS_LIMIT=20
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - WEAVIATE_DEFAULT_CONTEXTIONARY=english
      - WEAVIATE_HTTP_HOST=0.0.0.0 # HTTP 요청을 모든 IP에서 받도록 설정
      - WEAVIATE_GRPC_HOST=0.0.0.0 # gRPC 요청도 모든 IP에서 받도록 설정
    ports:
      - "8080:8080" # 외부에서 8080 포트로 접속 가능
    volumes:
      - weaviate_data:/weaviate_db
    networks:
      - weaviate_network

volumes:
  weaviate_data:

networks:
  weaviate_network:
    driver: bridge
